model:
  model_path: /mnt/d/cl/Qwen2.5-Omni/model
  processor_path: /mnt/d/cl/Qwen2.5-Omni/processor
  local_files_only: true
  attn_implementation: sdpa
  torch_dtype: auto

projection:
  mode: shared
  embed_dim: 1024
  normalize: true

loss:
  mode: inverse_volume
  volume_scale: 10.0
  volume_eps: 1.0e-6
  temperature: 1.0

eval:
  name: msr_vtt
  cache_dir: /mnt/d/cl/mrl/data_cache/msrvtt_test
  anno_path: /mnt/d/data/msrvtt/test_silence_flitered_884.json
  video_dir: /mnt/d/data/msrvtt/data/all-video
  audio_dir: /mnt/d/data/msrvtt/data/all-audio
  checkpoint_dir: /mnt/d/cl/mrl/outputs/models/train_vast_inverse_volume_vision_cap-video-audio_lr1e-4_lora-r16-a32-d0.05_proj-shared-1024/step_0000000
  query_modality: vision_cap
  target_modality: video
  auxiliary_modalities:
    - audio
  use_audio_in_video: false
  audio_from_video_if_missing: false
  nframes:
  caption_selection: random
  num_workers: 8
